import { Customer, Deal, Task } from '../types/crm';
import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { DealRow, DealInsert, TaskRow, TaskInsert } from '../types/supabase';
import { isValidUUID, generateSecureId } from '../lib/analytics';

const STORAGE_KEY_CUSTOMERS = 'cm_crm_customers_v2';
const STORAGE_KEY_DEALS = 'cm_crm_deals_v2';
const STORAGE_KEY_TASKS = 'cm_crm_tasks_v2';
const STORAGE_KEY_TASKS_ID_MAP = 'cm_crm_tasks_id_map';

export const INITIAL_CUSTOMERS: Customer[] = [];
export const INITIAL_DEALS: Deal[] = [];
export const INITIAL_TASKS: Task[] = [];

// Helper para converter registro do Supabase (TaskRow) em modelo do Frontend (Task)
export const mapTaskRowToTask = (row: TaskRow): Task => ({
  id: row.id,
  title: row.title,
  dueDate: row.due_date || new Date().toISOString().split('T')[0],
  completed: row.completed,
  priority: row.priority || 'medium',
  leadId: row.lead_id || null,
  dealId: row.deal_id || null,
  userId: row.user_id,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

// Helper para obter ou gerar um UUID persistente e consistente para IDs de tarefas locais
export const getOrCreateTaskIdMapping = (localId: string): string => {
  if (isValidUUID(localId)) {
    return localId;
  }
  try {
    const saved = localStorage.getItem(STORAGE_KEY_TASKS_ID_MAP);
    const map: Record<string, string> = saved ? JSON.parse(saved) : {};
    if (map[localId] && isValidUUID(map[localId])) {
      return map[localId];
    }
    const newUuid = generateSecureId();
    map[localId] = newUuid;
    localStorage.setItem(STORAGE_KEY_TASKS_ID_MAP, JSON.stringify(map));
    return newUuid;
  } catch {
    return generateSecureId();
  }
};

// Helper para converter registro do Supabase (DealRow) em modelo do Frontend (Deal)
export const mapDealRowToDeal = (row: DealRow): Deal => ({
  id: row.id,
  title: row.title,
  customerId: row.customer_id,
  customerName: row.customer_name,
  value: Number(row.value) || 0,
  stage: row.stage,
  expectedCloseDate: row.expected_close_date || new Date().toISOString().split('T')[0],
  leadId: row.lead_id || null,
  currency: row.currency || 'EUR',
  isAutoGenerated: row.is_auto_generated ?? false,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  closedAt: row.closed_at || null,
  visitor_id: row.visitor_id || null,
  session_id: row.session_id || null,
  utm_source: row.utm_source || null,
  utm_medium: row.utm_medium || null,
  utm_campaign: row.utm_campaign || null,
  utm_term: row.utm_term || null,
  utm_content: row.utm_content || null,
  gclid: row.gclid || null,
  fbclid: row.fbclid || null,
  ttclid: row.ttclid || null,
  first_touch: row.first_touch || null,
  last_touch: row.last_touch || null,
  landing_page: row.landing_page || null,
  referrer: row.referrer || null,
});

// Assina mudanças em tempo real na tabela 'leads' do Supabase
export const subscribeToRealtimeLeads = (onUpdate: (leads: Customer[]) => void) => {
  if (!isSupabaseConfigured()) return () => {};

  try {
    const channel = supabase
      .channel('public_leads_realtime')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'leads' },
        async () => {
          console.log('⚡ [Realtime Supabase]: Nova atualização na tabela leads!');
          const freshLeads = await crmStorage.fetchSupabaseLeads();
          onUpdate(freshLeads);
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  } catch {
    return () => {};
  }
};

// Assina mudanças em tempo real na tabela 'deals' do Supabase
export const subscribeToRealtimeDeals = (onUpdate: (deals: Deal[]) => void) => {
  if (!isSupabaseConfigured()) return () => {};

  try {
    const channel = supabase
      .channel('public_deals_realtime')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'deals' },
        async () => {
          console.log('⚡ [Realtime Supabase]: Nova atualização na tabela deals!');
          const freshDeals = await crmStorage.fetchSupabaseDeals();
          onUpdate(freshDeals);
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  } catch {
    return () => {};
  }
};

export const crmStorage = {
  // Carrega clientes do localStorage
  loadCustomers(): Customer[] {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_CUSTOMERS);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed)) {
          return parsed;
        }
      }
    } catch {
      // ignore
    }
    return [];
  },

  saveCustomers(customers: Customer[]) {
    try {
      localStorage.setItem(STORAGE_KEY_CUSTOMERS, JSON.stringify(customers));
    } catch {
      // ignore
    }
  },

  // Carrega Oportunidades do LocalStorage (Fallback / Cache)
  loadDeals(): Deal[] {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_DEALS);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed)) {
          return parsed;
        }
      }
    } catch {
      // ignore
    }
    return [];
  },

  saveDeals(deals: Deal[]) {
    try {
      localStorage.setItem(STORAGE_KEY_DEALS, JSON.stringify(deals));
    } catch {
      // ignore
    }
  },

  // Busca Oportunidades diretamente do Supabase com fallback para LocalStorage
  async fetchSupabaseDeals(): Promise<Deal[]> {
    if (!isSupabaseConfigured()) {
      return this.loadDeals();
    }

    try {
      const { data, error } = await supabase
        .from('deals')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error('❌ [Supabase fetchSupabaseDeals Error]:', error.message, error.details || '', error.hint || '');
      } else if (data) {
        const deals = data.map(mapDealRowToDeal);
        // Se encontramos deals remotos, sincroniza/mescla com local e salva cache
        if (deals.length > 0) {
          this.saveDeals(deals);
          return deals;
        }
      }
    } catch (err) {
      console.warn('⚠️ [Supabase Deals Fetch Warning]: Servidor indisponível, usando cache local.', err);
    }

    return this.loadDeals();
  },

  // Persiste um Deal no Supabase e no LocalStorage
  async saveDealToSupabase(deal: Deal): Promise<{ success: boolean; data?: Deal; error?: any }> {
    // Normalização de ID: garante que o ID seja estritamente um UUID válido para Postgres
    const validUuid = isValidUUID(deal.id) ? deal.id : generateSecureId();
    deal.id = validUuid;

    // Atualiza cache local imediatamente para UI responsiva
    const currentLocal = this.loadDeals();
    const updatedLocal = [deal, ...currentLocal.filter((d) => d.id !== deal.id)];
    this.saveDeals(updatedLocal);

    if (!isSupabaseConfigured()) {
      return { success: false, error: 'Supabase não configurado' };
    }

    // Verifica se o usuário atual está autenticado antes de salvar no Supabase (RLS do CRM)
    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) {
      console.log('[DEALS MIGRATION] Não autenticado. Salvo localmente.');
      return { success: false, error: 'Usuário não autenticado' };
    }

    try {
      const payload: DealInsert = {
        id: validUuid,
        title: deal.title || 'Nova Oportunidade',
        customer_id: deal.customerId || 'contato_geral',
        customer_name: deal.customerName || 'Cliente Geral',
        value: Number(deal.value) || 0,
        stage: deal.stage || 'lead',
        expected_close_date: (deal.expectedCloseDate && deal.expectedCloseDate.trim()) ? deal.expectedCloseDate.trim() : null,
        lead_id: deal.leadId && isValidUUID(deal.leadId) ? deal.leadId : null,
        currency: deal.currency || 'EUR',
        is_auto_generated: deal.isAutoGenerated ?? false,
        closed_at: (deal.closedAt && deal.closedAt.trim()) ? deal.closedAt.trim() : null,
        visitor_id: deal.visitor_id || null,
        session_id: deal.session_id && isValidUUID(deal.session_id) ? deal.session_id : null,
        utm_source: deal.utm_source || null,
        utm_medium: deal.utm_medium || null,
        utm_campaign: deal.utm_campaign || null,
        utm_term: deal.utm_term || null,
        utm_content: deal.utm_content || null,
        gclid: deal.gclid || null,
        fbclid: deal.fbclid || null,
        ttclid: deal.ttclid || null,
        first_touch: deal.first_touch || null,
        last_touch: deal.last_touch || null,
        landing_page: deal.landing_page || null,
        referrer: deal.referrer || null,
      };

      const { data, error } = await supabase
        .from('deals')
        .upsert(payload)
        .select()
        .single();

      if (error) {
        console.error(`[DEALS MIGRATION] Erro ao enviar deal ${validUuid}: ${error.message} (Código: ${error.code || 'N/A'}, Detalhes: ${error.details || 'N/A'}, Hint: ${error.hint || 'N/A'})`);
        return { success: false, error };
      } else if (data) {
        const mapped = mapDealRowToDeal(data);
        const freshList = this.loadDeals().map((d) => (d.id === mapped.id ? mapped : d));
        this.saveDeals(freshList);
        return { success: true, data: mapped };
      }
    } catch (err: any) {
      console.error(`[DEALS MIGRATION] Erro de exceção ao enviar deal ${validUuid}:`, err?.message || err);
      return { success: false, error: err };
    }

    return { success: false, error: 'Erro desconhecido' };
  },

  // Atualiza o Estágio do Deal no Supabase (com atualização rigorosa de closed_at)
  async updateDealStageInSupabase(dealId: string, stage: Deal['stage']): Promise<void> {
    const isClosed = stage === 'won' || stage === 'lost';
    
    // Atualização imediata em cache local
    const currentLocal = this.loadDeals();
    let calculatedClosedAt: string | null = null;

    const updatedLocal = currentLocal.map((d) => {
      if (d.id === dealId) {
        calculatedClosedAt = isClosed ? (d.closedAt || new Date().toISOString()) : null;
        return {
          ...d,
          stage,
          closedAt: calculatedClosedAt,
          updatedAt: new Date().toISOString(),
        };
      }
      return d;
    });
    this.saveDeals(updatedLocal);

    if (!isSupabaseConfigured()) return;

    // Garante sessão autenticada para escrita
    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) return;

    try {
      const { error } = await supabase
        .from('deals')
        .update({
          stage,
          closed_at: calculatedClosedAt,
          updated_at: new Date().toISOString(),
        })
        .eq('id', dealId);

      if (error) {
        console.error('❌ [Supabase updateDealStage Error]:', error.message, error.details || '', error.hint || '');
      }
    } catch (err) {
      console.error('❌ [Supabase updateDealStage Exception]:', err);
    }
  },

  // Exclui um Deal do Supabase e do LocalStorage
  async deleteDealFromSupabase(dealId: string): Promise<void> {
    const currentLocal = this.loadDeals();
    const updatedLocal = currentLocal.filter((d) => d.id !== dealId);
    this.saveDeals(updatedLocal);

    if (!isSupabaseConfigured()) return;

    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) return;

    try {
      const { error } = await supabase.from('deals').delete().eq('id', dealId);
      if (error) {
        console.error('❌ [Supabase deleteDeal Error]:', error.message, error.details || '', error.hint || '');
      }
    } catch (err) {
      console.error('❌ [Supabase deleteDeal Exception]:', err);
    }
  },

  // Insere um lead vindo do site diretamente no CRM local e no Supabase (Clientes + Negócios)
  addCustomerFromLead(lead: any, leadId?: string): { customer: Customer; deal?: Deal } {
    const currentCustomers = this.loadCustomers();
    const id = leadId || `lead_${Date.now()}`;
    
    const newCustomer: Customer = {
      id,
      name: lead.full_name,
      email: lead.email,
      phone: lead.phone,
      company: lead.company_name || 'Contato do Site',
      status: (lead.status === 'fechado_ganho' ? 'active' : 'lead') as Customer['status'],
      createdAt: new Date().toLocaleDateString('pt-BR'),
      source: lead.source || 'website',
      utm_source: lead.utm_source || undefined,
      utm_campaign: lead.utm_campaign || undefined,
    };

    const updatedCustomers = [newCustomer, ...currentCustomers.filter((c) => c.id !== id)];
    this.saveCustomers(updatedCustomers);

    // Cria a oportunidade no Funil de Vendas (Pipeline) com Atribuição Integrada
    let newDeal: Deal | undefined;
    if (lead.package_interest || lead.estimated_budget_eur) {
      const pkgName = (lead.package_interest || 'pro').toUpperCase();
      const value = lead.estimated_budget_eur ? Number(lead.estimated_budget_eur) : 299;
      const validLeadUuid = leadId && isValidUUID(leadId) ? leadId : null;

      newDeal = {
        id: generateSecureId(), // ID UUID Válido
        title: `Projeto Website ${pkgName} - ${lead.company_name || lead.full_name}`,
        customerId: id,
        customerName: lead.full_name,
        value,
        stage: 'lead',
        expectedCloseDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        leadId: validLeadUuid,
        currency: 'EUR',
        isAutoGenerated: true, // Marcação explícita para deduplicação automática
        createdAt: new Date().toISOString(),

        // Atribuição de Marketing Copiada Imediatamente do Lead
        visitor_id: lead.visitor_id || null,
        session_id: lead.session_id && isValidUUID(lead.session_id) ? lead.session_id : null,
        utm_source: lead.utm_source || null,
        utm_medium: lead.utm_medium || null,
        utm_campaign: lead.utm_campaign || null,
        utm_term: lead.utm_term || null,
        utm_content: lead.utm_content || null,
        gclid: lead.gclid || null,
        fbclid: lead.fbclid || null,
        ttclid: lead.ttclid || null,
        first_touch: lead.first_touch || null,
        last_touch: lead.last_touch || null,
        landing_page: lead.landing_page || null,
        referrer: lead.referrer || null,
      };

      // Tenta salvar assincronamente (se autenticado salva no Supabase; caso contrário guarda localmente)
      this.saveDealToSupabase(newDeal);
    }

    // Notifica em tempo real para atualização imediata de telas ativas do CRM
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('cm_lead_submitted', { detail: { customer: newCustomer, deal: newDeal } }));
    }

    return { customer: newCustomer, deal: newDeal };
  },

  // Migra Deals legados salvos no LocalStorage para o Supabase de forma segura e autenticada
  async migrateLocalDealsToSupabase(): Promise<{ totalLocal: number; migrated: number; failed: number }> {
    if (!isSupabaseConfigured()) {
      console.warn('[DEALS MIGRATION] Supabase não configurado');
      return { totalLocal: 0, migrated: 0, failed: 0 };
    }

    const localDeals = this.loadDeals();
    console.warn(`[DEALS MIGRATION] ${localDeals.length} encontrados no LocalStorage`);

    if (localDeals.length === 0) {
      return { totalLocal: 0, migrated: 0, failed: 0 };
    }

    // Só executa se houver administrador autenticado para passar pelo RLS
    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) {
      console.warn('[DEALS MIGRATION] Não autenticado. Migração em nuvem aguarda login de administrador.');
      return { totalLocal: localDeals.length, migrated: 0, failed: 0 };
    }

    console.warn(`[DEALS MIGRATION] Autenticado: Sim (Session UID: ${authData.session.user.id})`);
    console.warn(`[DEALS MIGRATION] Enviando ${localDeals.length} deals ao Supabase...`);

    let successCount = 0;
    let failCount = 0;

    try {
      // 1. Consulta deals já existentes no Supabase
      const { data: existingSupabaseDeals, error: fetchErr } = await supabase
        .from('deals')
        .select('id, lead_id, customer_id, is_auto_generated');

      if (fetchErr) {
        console.error(`[DEALS MIGRATION] Erro ao consultar deals no Supabase: ${fetchErr.message} (Código: ${fetchErr.code || 'N/A'}, Detalhes: ${fetchErr.details || 'N/A'})`);
      }

      const existingIds = new Set((existingSupabaseDeals || []).map((d) => d.id));
      const existingAutoLeadIds = new Set(
        (existingSupabaseDeals || [])
          .filter((d) => d.is_auto_generated && d.lead_id)
          .map((d) => d.lead_id)
      );

      let localStateModified = false;

      for (const deal of localDeals) {
        // Normalização de ID antigo (e.g. d_c_123 ou d_123456) para UUID Válido
        if (!isValidUUID(deal.id)) {
          const oldId = deal.id;
          deal.id = generateSecureId();
          console.log(`[DEALS MIGRATION] ID antigo ${oldId} convertido para UUID seguro ${deal.id}`);
          localStateModified = true;
        }

        // Se já existe no Supabase por ID, considera migrado
        if (existingIds.has(deal.id)) {
          console.log(`[DEALS MIGRATION] Deal ${deal.id} já existe no Supabase (pulando envio)`);
          successCount++;
          continue;
        }

        // Se for um Deal Automático e o lead_id já possui Deal Automático no Supabase, pula para evitar duplicação
        if (deal.isAutoGenerated && deal.leadId && existingAutoLeadIds.has(deal.leadId)) {
          console.log(`[DEALS MIGRATION] Deal automático para lead ${deal.leadId} já existe no Supabase (pulando envio)`);
          successCount++;
          continue;
        }

        // Tenta vincular ao lead original e recuperar atribuição de marketing se houver leadId ou customerId válido
        let leadAttribution: any = null;
        const targetLeadId = (deal.leadId && isValidUUID(deal.leadId)) 
          ? deal.leadId 
          : (deal.customerId && isValidUUID(deal.customerId) ? deal.customerId : null);

        if (targetLeadId) {
          try {
            const { data: leadData } = await supabase
              .from('leads')
              .select('*')
              .eq('id', targetLeadId)
              .maybeSingle();

            if (leadData) {
              leadAttribution = leadData;
            }
          } catch {
            // ignore
          }
        }

        const enrichedDeal: Deal = {
          ...deal,
          leadId: leadAttribution ? leadAttribution.id : (deal.leadId && isValidUUID(deal.leadId) ? deal.leadId : null),
          visitor_id: deal.visitor_id || (leadAttribution ? leadAttribution.visitor_id : null),
          session_id: deal.session_id || (leadAttribution ? leadAttribution.session_id : null),
          utm_source: deal.utm_source || (leadAttribution ? leadAttribution.utm_source : null),
          utm_medium: deal.utm_medium || (leadAttribution ? leadAttribution.utm_medium : null),
          utm_campaign: deal.utm_campaign || (leadAttribution ? leadAttribution.utm_campaign : null),
          utm_term: deal.utm_term || (leadAttribution ? leadAttribution.utm_term : null),
          utm_content: deal.utm_content || (leadAttribution ? leadAttribution.utm_content : null),
          gclid: deal.gclid || (leadAttribution ? leadAttribution.gclid : null),
          fbclid: deal.fbclid || (leadAttribution ? leadAttribution.fbclid : null),
          ttclid: deal.ttclid || (leadAttribution ? leadAttribution.ttclid : null),
          first_touch: deal.first_touch || (leadAttribution ? leadAttribution.first_touch : null),
          last_touch: deal.last_touch || (leadAttribution ? leadAttribution.last_touch : null),
          landing_page: deal.landing_page || (leadAttribution ? leadAttribution.landing_page : null),
          referrer: deal.referrer || (leadAttribution ? leadAttribution.referrer : null),
        };

        const res = await this.saveDealToSupabase(enrichedDeal);

        if (res.success) {
          console.log(`[DEALS MIGRATION] Inserido/Atualizado com sucesso: deal_id=${enrichedDeal.id}, lead_id=${enrichedDeal.leadId || 'null'}`);
          successCount++;
          existingIds.add(enrichedDeal.id);
          if (enrichedDeal.isAutoGenerated && enrichedDeal.leadId) {
            existingAutoLeadIds.add(enrichedDeal.leadId);
          }
        } else {
          console.error(`[DEALS MIGRATION] Erro ao enviar deal ${enrichedDeal.id}:`, res.error?.message || res.error || 'Erro desconhecido');
          failCount++;
        }
      }

      if (localStateModified) {
        this.saveDeals(localDeals);
      }
    } catch (err: any) {
      console.error('[DEALS MIGRATION] Erro na execução da migração:', err?.message || err);
    }

    console.log(`[DEALS MIGRATION] Concluído: ${successCount} migrados, ${failCount} falharam`);
    return { totalLocal: localDeals.length, migrated: successCount, failed: failCount };
  },

  // Carrega Tarefas do LocalStorage (Fallback / Cache)
  loadTasks(): Task[] {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_TASKS);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed)) {
          return parsed;
        }
      }
    } catch {
      // ignore
    }
    return [];
  },

  saveTasks(tasks: Task[]) {
    try {
      localStorage.setItem(STORAGE_KEY_TASKS, JSON.stringify(tasks));
    } catch {
      // ignore
    }
  },

  // Busca Tarefas diretamente do Supabase para o usuário autenticado com fallback para LocalStorage
  async fetchSupabaseTasks(): Promise<Task[]> {
    if (!isSupabaseConfigured()) {
      return this.loadTasks();
    }

    try {
      const { data: authData } = await supabase.auth.getSession();
      if (!authData.session) {
        return this.loadTasks();
      }

      const { data, error } = await supabase
        .from('tasks')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error('❌ [Supabase fetchSupabaseTasks Error]:', error.message);
      } else if (data) {
        const remoteTasks = data.map(mapTaskRowToTask);
        this.saveTasks(remoteTasks);
        return remoteTasks;
      }
    } catch (err) {
      console.warn('⚠️ [Supabase Tasks Fetch Warning]: Servidor indisponível, usando cache local.', err);
    }

    return this.loadTasks();
  },

  // Persiste uma Tarefa no Supabase e atualiza o LocalStorage
  async saveTaskToSupabase(task: Task): Promise<{ success: boolean; data?: Task; error?: any }> {
    const validUuid = getOrCreateTaskIdMapping(task.id);
    task.id = validUuid;

    // Atualiza cache local imediatamente para UI responsiva
    const currentLocal = this.loadTasks();
    const updatedLocal = [task, ...currentLocal.filter((t) => t.id !== task.id)];
    this.saveTasks(updatedLocal);

    if (!isSupabaseConfigured()) {
      return { success: false, error: 'Supabase não configurado' };
    }

    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) {
      return { success: false, error: 'Usuário não autenticado' };
    }

    try {
      const payload: TaskInsert = {
        id: validUuid,
        user_id: authData.session.user.id,
        title: task.title.trim() || 'Nova Tarefa',
        due_date: (task.dueDate && task.dueDate.trim()) ? task.dueDate.trim() : null,
        completed: task.completed ?? false,
        priority: task.priority || 'medium',
        lead_id: task.leadId && isValidUUID(task.leadId) ? task.leadId : null,
        deal_id: task.dealId && isValidUUID(task.dealId) ? task.dealId : null,
      };

      if (task.createdAt && !isNaN(Date.parse(task.createdAt))) {
        payload.created_at = new Date(task.createdAt).toISOString();
      }

      const { data, error } = await supabase
        .from('tasks')
        .upsert(payload)
        .select()
        .single();

      if (error) {
        console.error(`[TASKS] Erro ao enviar tarefa ${validUuid}:`, error.message);
        return { success: false, error };
      } else if (data) {
        const mapped = mapTaskRowToTask(data);
        const freshList = this.loadTasks().map((t) => (t.id === mapped.id ? mapped : t));
        this.saveTasks(freshList);
        return { success: true, data: mapped };
      }
    } catch (err: any) {
      console.error(`[TASKS] Erro ao enviar tarefa ${validUuid}:`, err?.message || err);
      return { success: false, error: err };
    }

    return { success: false, error: 'Erro desconhecido' };
  },

  // Alterna a conclusão de uma Tarefa no Supabase e atualiza o LocalStorage
  async toggleTaskInSupabase(taskId: string, completed: boolean): Promise<void> {
    const currentLocal = this.loadTasks();
    const updatedLocal = currentLocal.map((t) =>
      t.id === taskId ? { ...t, completed, updatedAt: new Date().toISOString() } : t
    );
    this.saveTasks(updatedLocal);

    if (!isSupabaseConfigured()) return;

    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) return;

    try {
      const { error } = await supabase
        .from('tasks')
        .update({
          completed,
          updated_at: new Date().toISOString(),
        })
        .eq('id', taskId);

      if (error) {
        console.error('❌ [Supabase toggleTaskInSupabase Error]:', error.message);
      }
    } catch (err) {
      console.error('❌ [Supabase toggleTaskInSupabase Exception]:', err);
    }
  },

  // Exclui uma Tarefa do Supabase e atualiza o LocalStorage apenas se confirmado ou offline
  async deleteTaskFromSupabase(taskId: string): Promise<boolean> {
    if (!isSupabaseConfigured()) {
      const currentLocal = this.loadTasks();
      this.saveTasks(currentLocal.filter((t) => t.id !== taskId));
      return true;
    }

    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) {
      const currentLocal = this.loadTasks();
      this.saveTasks(currentLocal.filter((t) => t.id !== taskId));
      return true;
    }

    try {
      const { error } = await supabase.from('tasks').delete().eq('id', taskId);
      if (error) {
        console.error('❌ [Supabase deleteTaskFromSupabase Error]:', error.message);
        return false;
      }

      const currentLocal = this.loadTasks();
      this.saveTasks(currentLocal.filter((t) => t.id !== taskId));
      return true;
    } catch (err) {
      console.error('❌ [Supabase deleteTaskFromSupabase Exception]:', err);
      return false;
    }
  },

  // Migra tarefas locais ativas para o Supabase sem sobrescrever tarefas remotas existentes
  async migrateLocalTasksToSupabase(): Promise<{ totalLocal: number; inserted: number; alreadyExisting: number; failed: number }> {
    const stats = { totalLocal: 0, inserted: 0, alreadyExisting: 0, failed: 0 };

    if (!isSupabaseConfigured()) return stats;

    const { data: authData } = await supabase.auth.getSession();
    if (!authData.session) return stats;

    const userId = authData.session.user.id;
    const localTasks = this.loadTasks();
    stats.totalLocal = localTasks.length;

    if (localTasks.length === 0) return stats;

    // Busca IDs das tarefas já salvas no Supabase para proteção contra sobrescrita
    const existingRemoteIds = new Set<string>();
    try {
      const { data: remoteData } = await supabase.from('tasks').select('id');
      if (remoteData) {
        remoteData.forEach((r) => existingRemoteIds.add(r.id));
      }
    } catch {
      // ignore
    }

    const updatedLocalTasks: Task[] = [];

    for (const task of localTasks) {
      const targetUuid = getOrCreateTaskIdMapping(task.id);
      const normalizedTask = { ...task, id: targetUuid, userId };
      updatedLocalTasks.push(normalizedTask);

      if (existingRemoteIds.has(targetUuid)) {
        stats.alreadyExisting++;
        continue;
      }

      try {
        const payload: TaskInsert = {
          id: targetUuid,
          user_id: userId,
          title: task.title || 'Tarefa Importada',
          due_date: (task.dueDate && task.dueDate.trim()) ? task.dueDate.trim() : null,
          completed: task.completed ?? false,
          priority: task.priority || 'medium',
          lead_id: task.leadId && isValidUUID(task.leadId) ? task.leadId : null,
          deal_id: task.dealId && isValidUUID(task.dealId) ? task.dealId : null,
        };

        if (task.createdAt && !isNaN(Date.parse(task.createdAt))) {
          payload.created_at = new Date(task.createdAt).toISOString();
        }

        const { error } = await supabase.from('tasks').insert(payload);

        if (!error) {
          stats.inserted++;
          existingRemoteIds.add(targetUuid);
        } else {
          stats.failed++;
        }
      } catch {
        stats.failed++;
      }
    }

    this.saveTasks(updatedLocalTasks);
    try {
      localStorage.setItem('cm_crm_tasks_migrated_v1', 'true');
    } catch {
      // ignore
    }

    return stats;
  },

  // Sincroniza Leads do Servidor (/api/leads) e do Supabase com a lista do CRM
  async fetchSupabaseLeads(): Promise<Customer[]> {
    const combinedMap = new Map<string, Customer>();

    // 1. Tenta carregar os leads do endpoint no servidor (/api/leads)
    try {
      const serverRes = await fetch('/api/leads');
      const contentType = serverRes.headers.get('content-type') || '';
      if (serverRes.ok && contentType.includes('application/json')) {
        const json = await serverRes.json();
        if (json.success && Array.isArray(json.leads)) {
          json.leads.forEach((lead: any) => {
            combinedMap.set(lead.id, {
              id: lead.id,
              name: lead.full_name || 'Cliente Sem Nome',
              email: lead.email || '',
              phone: lead.phone || '',
              company: lead.company_name || 'Contato do Site',
              status: (lead.status === 'fechado_ganho' ? 'active' : 'lead') as Customer['status'],
              createdAt: lead.created_at ? new Date(lead.created_at).toLocaleDateString('pt-BR') : new Date().toLocaleDateString('pt-BR'),
              source: lead.source || undefined,
              utm_source: lead.utm_source || undefined,
              utm_campaign: lead.utm_campaign || undefined,
            });
          });
        }
      }
    } catch {
      // ignore
    }

    // 2. Tenta carregar do Supabase se configurado
    if (isSupabaseConfigured()) {
      try {
        const { data, error } = await supabase
          .from('leads')
          .select('*')
          .order('created_at', { ascending: false });

        if (!error && data && data.length > 0) {
          data.forEach((lead: any) => {
            if (!combinedMap.has(lead.id)) {
              combinedMap.set(lead.id, {
                id: lead.id,
                name: lead.full_name,
                email: lead.email,
                phone: lead.phone,
                company: lead.company_name || 'Contato do Site',
                status: (lead.status === 'fechado_ganho' ? 'active' : 'lead') as Customer['status'],
                createdAt: new Date(lead.created_at).toLocaleDateString('pt-BR'),
                source: lead.source || undefined,
                utm_source: lead.utm_source || undefined,
                utm_campaign: lead.utm_campaign || undefined,
              });
            }
          });
        }
      } catch {
        // ignore
      }
    }

    // 3. Merge dos leads locais gravados no localStorage
    try {
      const localSaved = localStorage.getItem('cm_studio_local_leads');
      if (localSaved) {
        const parsed = JSON.parse(localSaved);
        if (Array.isArray(parsed)) {
          parsed.forEach((lead: any) => {
            const leadId = lead.id || `local_${lead.phone}`;
            if (!combinedMap.has(leadId)) {
              combinedMap.set(leadId, {
                id: leadId,
                name: lead.full_name || 'Contato Local',
                email: lead.email || '',
                phone: lead.phone || '',
                company: lead.company_name || 'Contato do Site',
                status: (lead.status === 'fechado_ganho' ? 'active' : 'lead') as Customer['status'],
                createdAt: lead.created_at ? new Date(lead.created_at).toLocaleDateString('pt-BR') : new Date().toLocaleDateString('pt-BR'),
                source: lead.source || undefined,
                utm_source: lead.utm_source || undefined,
                utm_campaign: lead.utm_campaign || undefined,
              });
            }
          });
        }
      }
    } catch {
      // ignore
    }

    return Array.from(combinedMap.values());
  },

  // Salva lead no Supabase ao adicionar um novo cliente pelo CRM
  async syncCustomerToSupabase(customer: Omit<Customer, 'id' | 'createdAt'>) {
    if (!isSupabaseConfigured()) return;
    try {
      await supabase.from('leads').insert([
        {
          full_name: customer.name.trim().slice(0, 120),
          email: customer.email.trim().toLowerCase().slice(0, 150),
          phone: customer.phone.trim().slice(0, 40),
          company_name: customer.company ? customer.company.trim().slice(0, 120) : null,
          status: customer.status === 'active' ? 'fechado_ganho' : 'novo',
          source: 'crm_admin',
        },
      ]);
    } catch {
      // ignore
    }
  },
};
