export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  company: string;
  status: 'lead' | 'active' | 'inactive';
  createdAt: string;
  source?: string;
  utm_source?: string;
  utm_campaign?: string;
}

export interface Deal {
  id: string;
  title: string;
  customerId: string;
  customerName: string;
  value: number;
  stage: 'lead' | 'contact' | 'proposal' | 'negotiation' | 'won' | 'lost';
  expectedCloseDate: string;
  
  // Novos campos para Persistência e Atribuição de Receita (Fase 3)
  leadId?: string | null;
  currency?: string;
  isAutoGenerated?: boolean;
  createdAt?: string;
  updatedAt?: string;
  closedAt?: string | null;

  // Atribuição de Marketing (Copiados do Lead)
  visitor_id?: string | null;
  session_id?: string | null;
  utm_source?: string | null;
  utm_medium?: string | null;
  utm_campaign?: string | null;
  utm_term?: string | null;
  utm_content?: string | null;
  gclid?: string | null;
  fbclid?: string | null;
  ttclid?: string | null;
  first_touch?: any;
  last_touch?: any;
  landing_page?: string | null;
  referrer?: string | null;
}

export interface Task {
  id: string;
  title: string;
  dueDate: string;
  completed: boolean;
  priority: 'low' | 'medium' | 'high';
  customerId?: string; // Campo legado mantido para compatibilidade
  leadId?: string | null;
  dealId?: string | null;
  userId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type ViewType = 'dashboard' | 'customers' | 'deals' | 'tasks' | 'settings' | 'base-design';
