import React, { useState } from 'react';
import { Plus, DollarSign, Calendar, Building, Trash2 } from 'lucide-react';
import { Deal, Customer } from '../types/crm';
import { useLanguage } from '../context/LanguageContext';

interface DealsViewProps {
  deals: Deal[];
  customers: Customer[];
  onAddDeal: (deal: Omit<Deal, 'id'>) => void;
  onUpdateDealStage: (dealId: string, stage: Deal['stage']) => void;
  onDeleteDeal?: (dealId: string) => void;
}

export const DealsView: React.FC<DealsViewProps> = ({
  deals,
  customers,
  onAddDeal,
  onUpdateDealStage,
  onDeleteDeal,
}) => {
  const { t, formatCurrency, formatDate } = useLanguage();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [formData, setFormData] = useState({
    title: '',
    customerId: customers[0]?.id || '',
    customerName: customers[0]?.name || '',
    value: 5000,
    stage: 'lead' as Deal['stage'],
    expectedCloseDate: new Date().toISOString().split('T')[0],
  });

  const stages: { id: Deal['stage']; label: string; color: string }[] = [
    { id: 'lead', label: t('stageLead'), color: 'border-t-blue-500' },
    { id: 'contact', label: t('stageContact'), color: 'border-t-indigo-500' },
    { id: 'proposal', label: t('stageProposal'), color: 'border-t-purple-500' },
    { id: 'negotiation', label: t('stageNegotiation'), color: 'border-t-amber-500' },
    { id: 'won', label: t('stageWon'), color: 'border-t-emerald-500' },
  ];

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title.trim()) return;
    const selectedCustomer = customers.find((c) => c.id === formData.customerId);
    const validLeadId = selectedCustomer?.id && (selectedCustomer.id.includes('-') || selectedCustomer.id.length >= 20) ? selectedCustomer.id : null;

    onAddDeal({
      ...formData,
      customerName: selectedCustomer ? selectedCustomer.name : formData.customerName || 'Cliente Geral',
      leadId: validLeadId,
      currency: 'EUR',
      isAutoGenerated: false,
      createdAt: new Date().toISOString(),
      utm_source: selectedCustomer?.utm_source || null,
      utm_campaign: selectedCustomer?.utm_campaign || null,
    });
    setFormData({
      title: '',
      customerId: customers[0]?.id || '',
      customerName: customers[0]?.name || '',
      value: 5000,
      stage: 'lead',
      expectedCloseDate: new Date().toISOString().split('T')[0],
    });
    setIsModalOpen(false);
  };

  const totalValue = deals.reduce((sum, d) => sum + d.value, 0);

  return (
    <div className="space-y-4">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-slate-900">{t('dealsFunnelTitle')}</h3>
          <p className="text-xs text-slate-500">{t('dealsFunnelSubtitle')}</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="rounded-lg bg-blue-50 px-3 py-1.5 border border-blue-100">
            <span className="text-[11px] font-medium text-slate-600 mr-2">{t('totalPipelineValue')}:</span>
            <span className="text-xs font-bold text-blue-700">{formatCurrency(totalValue)}</span>
          </div>
          <button
            onClick={() => setIsModalOpen(true)}
            className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-3.5 py-2 text-xs font-semibold text-white shadow-xs hover:bg-blue-700 transition-colors"
          >
            <Plus className="h-4 w-4" />
            {t('modalNewDeal')}
          </button>
        </div>
      </div>

      {/* Kanban Board */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 items-start">
        {stages.map((stage) => {
          const stageDeals = deals.filter((d) => d.stage === stage.id);
          const stageTotal = stageDeals.reduce((sum, d) => sum + d.value, 0);

          return (
            <div
              key={stage.id}
              className={`flex flex-col rounded-xl border border-slate-200/80 bg-slate-50/60 p-3 shadow-2xs border-t-4 ${stage.color}`}
            >
              {/* Stage Header */}
              <div className="flex items-center justify-between pb-2 border-b border-slate-200">
                <span className="text-xs font-semibold text-slate-800">{stage.label}</span>
                <span className="rounded-full bg-slate-200 px-2 py-0.5 text-[10px] font-bold text-slate-700">
                  {stageDeals.length}
                </span>
              </div>
              <p className="text-[10px] text-slate-500 font-medium pt-1.5 pb-2">
                {formatCurrency(stageTotal)}
              </p>

              {/* Stage Cards */}
              <div className="space-y-2 min-h-32">
                {stageDeals.length === 0 ? (
                  <div className="flex h-28 items-center justify-center rounded-lg border border-dashed border-slate-200 p-3 text-center">
                    <p className="text-[11px] text-slate-400">{t('emptyStage')}</p>
                  </div>
                ) : (
                  stageDeals.map((deal) => (
                    <div
                      key={deal.id}
                      className="group rounded-lg border border-slate-200/80 bg-white p-3 shadow-2xs hover:shadow-xs transition-shadow relative"
                    >
                      <div className="flex items-start justify-between gap-1">
                        <h4 className="text-xs font-semibold text-slate-900 leading-snug">{deal.title}</h4>
                        {onDeleteDeal && (
                          <button
                            onClick={() => onDeleteDeal(deal.id)}
                            title="Excluir Oportunidade"
                            className="text-slate-300 hover:text-red-600 transition-colors p-0.5"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        )}
                      </div>
                      <p className="mt-1 flex items-center gap-1 text-[11px] text-slate-500 truncate">
                        <Building className="h-3 w-3 text-slate-400 shrink-0" />
                        {deal.customerName}
                      </p>

                      <div className="mt-2.5 flex items-center justify-between border-t border-slate-100 pt-2">
                        <span className="text-xs font-bold text-slate-800">
                          {formatCurrency(deal.value)}
                        </span>
                        <span className="flex items-center gap-1 text-[10px] text-slate-500">
                          <Calendar className="h-3 w-3 text-slate-400" />
                          {formatDate(deal.expectedCloseDate)}
                        </span>
                      </div>

                      {/* Quick stage mover */}
                      <div className="mt-2 pt-2 border-t border-slate-100/80 flex items-center justify-between text-[10px]">
                        <span className="text-slate-400">{t('stageMoveTo')}</span>
                        <select
                          value={deal.stage}
                          onChange={(e) => onUpdateDealStage(deal.id, e.target.value as Deal['stage'])}
                          className="rounded border border-slate-200 bg-white px-1.5 py-0.5 text-[10px] text-slate-700 focus:outline-hidden"
                        >
                          {stages.map((s) => (
                            <option key={s.id} value={s.id}>
                              {s.label}
                            </option>
                          ))}
                        </select>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Add Deal Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-2xs">
          <div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl animate-in fade-in-50 zoom-in-95 duration-150">
            <h3 className="text-base font-semibold text-slate-900">{t('modalNewDeal')}</h3>
            <form onSubmit={handleSubmit} className="mt-4 space-y-3.5">
              <div>
                <label className="block text-xs font-medium text-slate-700">{t('labelDealTitle')} *</label>
                <input
                  type="text"
                  required
                  placeholder={t('placeholderDealTitle')}
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-900 placeholder-slate-400 focus:border-blue-500 focus:outline-hidden"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-700">{t('labelCustomerAssoc')}</label>
                <select
                  value={formData.customerId}
                  onChange={(e) => {
                    const cust = customers.find((c) => c.id === e.target.value);
                    setFormData({
                      ...formData,
                      customerId: e.target.value,
                      customerName: cust ? cust.name : '',
                    });
                  }}
                  className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-900 focus:border-blue-500 focus:outline-hidden"
                >
                  {customers.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name} ({c.company})
                    </option>
                  ))}
                  {customers.length === 0 && (
                    <option value="">{t('selectCustomer')}</option>
                  )}
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-700">{t('labelDealValue')} *</label>
                <div className="relative mt-1">
                  <input
                    type="number"
                    min="0"
                    step="100"
                    required
                    value={formData.value}
                    onChange={(e) => setFormData({ ...formData, value: Number(e.target.value) })}
                    className="w-full rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-900 focus:border-blue-500 focus:outline-hidden"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-700">{t('labelStageField')}</label>
                <select
                  value={formData.stage}
                  onChange={(e) => setFormData({ ...formData, stage: e.target.value as Deal['stage'] })}
                  className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-900 focus:border-blue-500 focus:outline-hidden"
                >
                  {stages.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.label}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-700">{t('labelCloseDate')}</label>
                <input
                  type="date"
                  value={formData.expectedCloseDate}
                  onChange={(e) => setFormData({ ...formData, expectedCloseDate: e.target.value })}
                  className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-900 focus:border-blue-500 focus:outline-hidden"
                />
              </div>

              <div className="mt-5 flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50 transition-colors"
                >
                  {t('btnCancel')}
                </button>
                <button
                  type="submit"
                  className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-700 transition-colors"
                >
                  {t('btnSaveDeal')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
